articles/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('', views.article_list, name='list'),
    path('<slug:slug>/', views.article_detail, name='detail'),
]

shin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('about/', views.about),
    path('', views.homepage)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models


# Create your models here.
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thum = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse


# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/article_list.html', context)


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    context = {
        'article': article
    }
    return render(request, 'articles/article_detail.html', context)

shin/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage.html')


def about(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock title%}

{% block content %}
    <p>About Page</p>
{% endblock content  %}

templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
        <div class="article">
            <img src="{{ article.thum.url }}" alt="">
            <h3>{{ article.title }}</h3>
            <p>{{ article.body }}</p>
            <p><small>{{ article.date }}</small></p>
        </div>
{% endblock content  %}

templates/articles/article_list.html
{% extends 'base.html' %}

{% block content %}
    {% for article in articles %}
        <div class="article">
            <h3><a href="{% url 'article:detail' article.slug %}">{{ article.title }}</a></h3>
            <p><small>{{ article.date }}</small></p>
            <p>{{ article.snippet }}</p>
        </div>
    {% endfor %}
{% endblock content  %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %} Share Inspiration {% endblock title %}</title>
</head>
<body>

<div class="wrapper">
    {% block content %}
    {% endblock content %}
</div>

</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center">Welcome To Shin</h2>
    <p style="text-align: center"><a href="{% url 'article:list' %}">Check The Articles</a></p>
{% endblock content  %}